framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: snc_redis.session.handler
    php_errors:
        log: true
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%"
