<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Bh79aF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Bh79aF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7Bh79aF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7Bh79aF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7Bh79aF\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7Bh79aF',
    'container.build_id' => '443e4b7f',
    'container.build_time' => 1535399259,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7Bh79aF');
